[package]
name = "dice"
version = "0.1.2"
authors = ["Alyssa Riceman <altoftulip@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rust_decimal = "1.14"
iced = "0.3"
